;같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같
;
; Filename     : font2.inc
; Included from: font.asm
; Description  : _font0.inc and _font1.inc letter length tables
;
; Written by: John McCarthy
;             1316 Redwood Lane
;             Pickering, Ontario.
;             Canada, Earth, Milky Way (for those out-of-towners)
;             L1X 1C5
;
; Internet/Usenet:  BRIAN.MCCARTHY@CANREM.COM
;         Fidonet:  Brian McCarthy 1:229/15
;   RIME/Relaynet: ->CRS
;
; Home phone, (905) 831-1944, don't call at 2 am eh!
;
; John Mccarthy would really love to work for a company programming Robots
; or doing some high intensive CPU work.  Hint. Hint.
;
; Send me your protected mode source code!
; Send me your Objects!
; But most of all, Send me a postcard!!!!
;
;같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같

_fontlength dw 9,9,9,9,9,9,9,9,9,9          ; length of letters for _font0
         dw 9,9,9,9,9,9,9,9,9,9
         dw 9,9,9,9,9,9,9,9,9,9
         dw 9,9,9,9,9,9,9,9,9,9             ; 30-39
         dw 9,9,9,9,9,9,9,9,9,9
         dw 9,9,9,9,9,9,9,9,9,9
         dw 9,9,9,9,9,9,9,9,9,9             ; 60-69   ;      abcde
         dw 9,9,9,9,9,9,9,9,9,9             ; 70-79   ; fghijklmno
         dw 9,9,9,9,9,9,9,9,9,9             ; 80-89   ; pqrstuvwxy
         dw 9,9,9,9,9,9,9,9,9,9             ; 90-99   ; z      abc
         dw 9,9,9,9,9,9,9,9,9,9             ; 100-109 ; defghijklm
         dw 9,9,9,9,9,9,9,9,9,9             ; 110-119 ; nopqrstuvw
         dw 9,9,9,9,9,9,9,9                 ; 120-128 ; xyz

         dw 9,9,9,9,9,9,9,9,9,9             ; length of letters for _font1
         dw 9,9,9,9,9,9,9,9,9,9
         dw 9,9,9,9,9,9,9,9,9,9
         dw 9,9,9,9,9,9,9,9,9,9             ; 30-39
         dw 9,9,9,9,9,9,9,9,9,9
         dw 9,9,9,9,9,9,9,9,9,9
         dw 9,9,9,9,9,9,9,9,9,9             ; 60-69   ;      abcde
         dw 9,9,9,9,9,9,9,9,9,9             ; 70-79   ; fghijklmno
         dw 9,9,9,9,9,9,9,9,9,9             ; 80-89   ; pqrstuvwxy
         dw 9,9,9,9,9,9,9,9,9,9             ; 90-99   ; z      abc
         dw 9,9,9,9,9,9,9,9,9,9             ; 100-109 ; defghijklm
         dw 9,9,9,9,9,9,9,9,9,9             ; 110-119 ; nopqrstuvw
         dw 9,9,9,9,9,9,9,9                 ; 120-128 ; xyz

